image: docker:stable

variables:
  DOCKER_DRIVER: overlay
  DOCKER_REGISTRY: 922924176525.dkr.ecr.us-east-2.amazonaws.com
  APP_NAME: starwars-api
  DOCKER_HOST: tcp://docker:2375
  AWS_REGION: us-east-2

stages:
   - test
   - build
   - build_image
   - deploy

before_script:
  - chmod +x mvnw

test:
  image: java:8
  stage: test
  script: ./mvnw test

build:
  image: java:8
  stage: build
  script: ./mvnw package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/b2w-starwars-api-1.0.1.jar

build_image:
  stage: build_image
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
  - docker:dind
  before_script:
  - amazon-linux-extras install docker
  - aws --version
  - docker --version
  script: 
      - docker build --tag $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
      - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
      - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws ecs register-task-definition --region us-east-2 --family MyTaskDef --cli-input-json file://ecs-task-definition.json
    - aws ecs update-service --region us-east-2 --cluster StarCluster --service StarService --task-definition MyTaskDef