image: java:8

stages:
   - test
   - build

before_script:
  - chmod +x mvnw

test:
  stage: test
  script: ./mvnw test

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/b2w-starwars-api-1.0.1.jar

docker_build:
	stage: docker_build
	script: docker build --tag starwars-api:1.0.1